name: build

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  main-linux:
   uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
   with:
      env: '["py37", "py38", "py39", "py310"]'
      os: ubuntu-latest
  cov:
    runs-on: ubuntu-latest
    needs: [main-linux]
    steps:
      - uses: actions/checkout@master
      - name: Generate coverage report
        run: |
          pip install -r requirements-dev.txt
          pip install .
          pytest --cov=./ --cov-report=xml --cov-fail-under=98
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # not required for public repos
          files: ./coverage.xml  # optional
          flags: unittests  # optional
          name: codecov-umbrella  # optional
          fail_ci_if_error: true  # optional (default = false)
          verbose: true  # optional (default = false)
